name: safescene-ai
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch>=2.0.0
  - torchvision>=0.15.0
  - pytorch-cuda=11.8
  - cudatoolkit=11.8
  - pip
  - jupyter
  - ipykernel
  - pip:
    - stable-baselines3>=2.0.0
    - fastapi>=0.100.0
    - streamlit>=1.25.0
    - wandb>=0.15.0
    - opencv-python>=4.8.0
    - pytorch-fid
    - lpips
    - kornia>=0.7.0
    - albumentations>=1.3.0
    - hydra-core>=1.3.0
